<?php

$curl = curl_init();
$channel =$_GET['c'];

$url="https://spapi.zee5.com/singlePlayback/getDetails/secure?channel_id=$channel&device_id=euqEbXxM2dHIyYg9E8zp000000000000&platform_name=mobile_web&translation=en&user_language=mr&country=IN&state=UP&app_version=3.15.17&user_type=premium&check_parental_control=false&uid=a72f20ea-6bd7-40fc-bc5a-da97aed4b637&ppid=euqEbXxM2dHIyYg9E8zp000000000000&version=12";

curl_setopt_array($curl, array(
  CURLOPT_URL => $url,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
  "x-access-token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF0Zm9ybV9jb2RlIjoiV2ViQCQhdDM4NzEyIiwiaXNzdWVkQXQiOiIyMDIzLTEyLTA0VDA2OjM1OjExLjQ0NFoiLCJwcm9kdWN0X2NvZGUiOiJ6ZWU1QDk3NSIsInR0bCI6ODY0MDAwMDAsImlhdCI6MTcwMTY3MTcxMX0.v2LmiKxhEQGm1N8uq_JAEbB7WxUjxqYv0K2owuOVkDM",  
  "Authorization": "eyJraWQiOiJlNmxfbGYweHpwYVk4VzBNcFQzWlBzN2hyOEZ4Y0trbDhDV0JaekVKT2lBIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJBNzJGMjBFQS02QkQ3LTQwRkMtQkM1QS1EQTk3QUVENEI2MzciLCJzdWJzY3JpcHRpb25zIjoiW3tcImlkXCI6XCI2MGQ4M2Q1OS04MmRhLTQyNDAtYmM3NC1lZWMxNjY1OWI3MTdcIixcInVzZXJfaWRcIjpcImE3MmYyMGVhLTZiZDctNDBmYy1iYzVhLWRhOTdhZWQ0YjYzN1wiLFwiaWRlbnRpZmllclwiOlwiQ1JNXCIsXCJzdWJzY3JpcHRpb25fcGxhblwiOntcImlkXCI6XCIwLTExLTIwNjVcIixcImFzc2V0X3R5cGVcIjoxMSxcInN1YnNjcmlwdGlvbl9wbGFuX3R5cGVcIjpcIlNWT0RcIixcInRpdGxlXCI6XCJaRUU1IFByZW1pdW1cIixcIm9yaWdpbmFsX3RpdGxlXCI6XCJaRUU1IFByZW1pdW1cIixcInN5c3RlbVwiOlwiQlNOTFwiLFwiZGVzY3JpcHRpb25cIjpcIlpFRTUgUHJlbWl1bVwiLFwiYmlsbGluZ19jeWNsZV90eXBlXCI6XCJkYXlzXCIsXCJiaWxsaW5nX2ZyZXF1ZW5jeVwiOjM2NSxcInByaWNlXCI6MCxcImN1cnJlbmN5XCI6XCJJTlJcIixcImNvdW50cnlcIjpcIklOXCIsXCJjb3VudHJpZXNcIjpbXCJJTlwiXSxcInN0YXJ0XCI6XCIyMDIyLTAyLTE1VDE1OjU1OjAwWlwiLFwiZW5kXCI6XCIyMDI0LTAzLTMxVDE1OjU1OjAwWlwiLFwib25seV9hdmFpbGFibGVfd2l0aF9wcm9tb3Rpb25cIjpmYWxzZSxcInJlY3VycmluZ1wiOmZhbHNlLFwicGF5bWVudF9wcm92aWRlcnNcIjpbe1wibmFtZVwiOlwiY3JtXCIsXCJwcm9kdWN0X3JlZmVyZW5jZVwiOm51bGx9XSxcInByb21vdGlvbnNcIjpbXSxcImFzc2V0X3R5cGVzXCI6WzAsNiw5XSxcImFzc2V0X2lkc1wiOltcIlwiXSxcImZyZWVfdHJpYWxcIjowLFwiYnVzaW5lc3NfdHlwZVwiOlwiZnJlZVwiLFwiYmlsbGluZ190eXBlXCI6XCJwcmVtaXVtXCIsXCJudW1iZXJfb2Zfc3VwcG9ydGVkX2RldmljZXNcIjoxLFwibW92aWVfYXVkaW9fbGFuZ3VhZ2VzXCI6W10sXCJ0dl9zaG93X2F1ZGlvX2xhbmd1YWdlc1wiOltdLFwiY2hhbm5lbF9hdWRpb19sYW5ndWFnZXNcIjpbXSxcImR1cmF0aW9uX3RleHRcIjpcIlwiLFwidmFsaWRfZm9yX2FsbF9jb3VudHJpZXNcIjp0cnVlLFwiYWxsb3dlZF9wbGF5YmFja19kdXJhdGlvblwiOjYsXCJvZmZlcl9pZFwiOjAsXCJjYXRlZ29yeVwiOlwiZGVmYXVsdFwiLFwiYWN0dWFsX3ZhbHVlXCI6MCxcImJlZm9yZVR2XCI6dHJ1ZX0sXCJzdWJzY3JpcHRpb25fc3RhcnRcIjpcIjIwMjMtMDEtMTBUMDI6NTA6NDUuNDAzWlwiLFwic3Vic2NyaXB0aW9uX2VuZFwiOlwiMjAyNC0wMS0xMFQyMzo1OTo1OVpcIixcInN0YXRlXCI6XCJhY3RpdmF0ZWRcIixcInJlY3VycmluZ19lbmFibGVkXCI6ZmFsc2UsXCJwYXltZW50X3Byb3ZpZGVyXCI6bnVsbCxcImZyZWVfdHJpYWxcIjpudWxsLFwiY3JlYXRlX2RhdGVcIjpudWxsLFwiaXBfYWRkcmVzc1wiOlwiNjUuMC40MC4xMzVcIixcImNvdW50cnlcIjpcIklOXCIsXCJhZGRpdGlvbmFsXCI6e1wic291cmNlXCI6XCJCMkJBUElcIixcInBhcnRuZXJcIjpcImh0bWVkaWFcIixcInVzZWRfYmlsbF9jeWNsZVwiOjB9LFwiYWxsb3dlZF9iaWxsaW5nX2N5Y2xlc1wiOjAsXCJ1c2VkX2JpbGxpbmdfY3ljbGVzXCI6MH1dIiwiYWN0aXZhdGlvbl9kYXRlIjoiMjAxOC0xMi0yMFQxMzozMDo0Ni4xNDBaIiwiYW1yIjpbImRlbGVnYXRpb24iXSwiaXNzIjoiaHR0cHM6Ly91c2VyYXBpLnplZTUuY29tIiwiY3VycmVudF9jb3VudHJ5IjoiSU4iLCJjbGllbnRfaWQiOiJyZWZyZXNoX3Rva2VuIiwiYWNjZXNzX3Rva2VuX3R5cGUiOiJEZWZhdWx0UHJpdmlsZWdlIiwidXNlcl90eXBlIjoiUmVnaXN0ZXJlZCIsInVzZXJfbW9iaWxlIjoiOTE4NjY4NjM0NTAyIiwic2NvcGUiOlsidXNlcmFwaSIsInN1YnNjcmlwdGlvbmFwaSIsInByb2ZpbGVhcGkiXSwiYXV0aF90aW1lIjoxNzAxNDE0MjE0LCJleHAiOjE3MDQwNDQyMTQsImlhdCI6MTcwMTQxNDIxNCwianRpIjoiYjZiMTdhZTItMmNiYi00NWQ3LThlYTktODA5NzY1ODBiNTdiIiwiZGV2aWNlX2lkIjoiZXVxRWJYeE0yZEhJeVlnOUU4enAwMDAwMDAwMDAwMDAiLCJyZWdpc3RyYXRpb25fY291bnRyeSI6IklOIiwidmVyc2lvbiI6NSwiYXVkIjpbInVzZXJhcGkiLCJzdWJzY3JpcHRpb25hcGkiLCJwcm9maWxlYXBpIl0sInN5c3RlbSI6Ilo1IiwibmJmIjoxNzAxNDE0MjE0LCJpZHAiOiJsb2NhbCIsInVzZXJfaWQiOiJhNzJmMjBlYS02YmQ3LTQwZmMtYmM1YS1kYTk3YWVkNGI2MzciLCJjcmVhdGVkX2RhdGUiOiIyMDE4LTEyLTIwVDEzOjMwOjQ2LjE0MFoiLCJhY3RpdmF0ZWQiOnRydWV9.NOtzkP7ofm16Qs6qnmHRtzMgCQoPlNwmXVe6MkfYKlVUhWD1v3JfbzPlh49Demqe-PPCgJLP_b4HEQEToHRNW8-cf_-RnMJMM-XaMwdiyj2RArNnkkinUBbnWTfYd0Vqk0QLsL7FTrzmHFfDxkh4khKm0eOdxrwQ8A8ElFflS_paWvqf2EjU3ozjUZEa8kz5xpHEolrC0axJ-bTv10Ft6aSLWfgbk4d2DIV7Q89haojMG5AwMGF87DcZdisb0Ei8u31sawSy8xNfFFGB00h-kpdLMHywm7fyq-qsETks-T2nVxgNys7ZitvBKRZNXpVTvhVQeqCoPEXuijnHp3GVxg"
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json'
  ),
));


$response = curl_exec($curl);
curl_close($curl);

$zx = json_decode($response, true);
$image= $zx["assetDetails"]['image_url'];
$img = str_replace('270x152', '1170x658', $image);
$title= $zx["assetDetails"]['title'];
$des= $zx["assetDetails"]['description'];
$playit= $zx["keyOsDetails"]['video_token'];



header("Location: $playit");

?>